version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fileit
      POSTGRES_DB: fileit

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080


#  app:
#    build:
#      context: .
#      dockerfile: dev.Dockerfile
#    ports:
#      - 5000:5000
